import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import ClientLayoutWrapper from "@/Components/LayoutWrapar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rightmove",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
     <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header/> */}
        <ClientLayoutWrapper>
        {children}
        </ClientLayoutWrapper>
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
  );
}
